name: 'Hello World'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sample:
    name: Hello World Job
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World !"
      - run: mysql -V
      - run: git -v
      - run: |
          echo "Hello ${{ env.MESSAGE }}"
          echo "Hello ${env.MESSAGE}"
          echo "Hello ${MESSAGE}"
        env:
          MESSAGE: 'world'
